name: flutter_authgear_example
description: Demonstrates how to use flutter_authgear

publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  flutter_authgear: ^1.7.0
  package_info_plus: 4.2.0
  authgear_sdk_tool_migrate_xamarin_flutter:
    git:
      url: https://github.com/authgear/authgear-tool-migrate-xamarin-flutter
      path: migratetool
      ref: v0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
