name: authgear_sdk_tool_migrate_xamarin_flutter
description: Authgear Migrate Tool For Xamarin To Flutter
repository: https://github.com/authgear/authgear-tool-migrate-xamarin-flutter/migratetool
version: 0.2.0

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.authgear.sdk.migrateplugin.xamarinflutter
        pluginClass: MigratetoolPlugin
      ios:
        pluginClass: MigratetoolPlugin
